name 'libpri'
maintainer 'Jeremy Woertink'
maintainer_email 'jeremywoertink@gmail.com'
license 'WTFPL'
description 'Installs/Configures libpri'
long_description 'Installs/Configures libpri'
version '0.1.0'
