#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

source "https://supermarket.getchef.com"

cookbook 'apache', path: 'cookbooks/apache'
cookbook 'dependencies', path: 'cookbooks/dependencies'
cookbook 'pjproject', path: 'cookbooks/pjproject'
cookbook 'asterisk', path: 'cookbooks/asterisk'
cookbook 'ejabberd', path: 'cookbooks/ejabberd'

# Optional addons for asterisk
# cookbook 'freepbx', path: 'cookbooks/freepbx'
# cookbook 'dahdi', path: 'cookbooks/dahdi'
# cookbook 'dahdi-tools', path: 'cookbooks/dahdi-tools'
# cookbook 'libpri', path: 'cookbooks/libpri'
