# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "xcezx/centos6.5-with-ansible"
  config.vm.hostname = "pbx.local"

  config.vm.network "public_network", ip: "0.0.0.0"

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "AnsiblePBX"
    vbox.memory = 512
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
